blank_issues_enabled: false

contact_links:
  - name: GitHub Issues
    url: "https://github.com/eser/tools/issues"
    about: Ask questions and discuss ideas
#   - name: Discord
#     url: "{{DISCORD_URL}}"
#     about: Chat with the community
